apiVersion: v1
kind: ReplicationController
metadata:
  name: hub-federator
  labels:
    name: hub-federator
spec:
  replicas: 1
  selector:
    name: hub-federator
  template:
    metadata:
      labels:
        name: hub-federator
    spec:
      volumes:
      - configMap:
          defaultMode: 420
          name: hubfederator
        name: hubfederator
      containers:
      - name: hub-federator
        image: gcr.io/gke-verification/blackducksoftware/federator:hub
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/hubfederator
          name: hubfederator
        args:
        - /etc/hubfederator/config.json
        command:
        - ./federator
        ports:
        - containerPort: 3016
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: HUB_PASSWORD
          value: <TODO_SET_ME>
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
